name: base
channels:
  - pytorch
  - nvidia
  - main
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - abseil-cpp=20200923.3=h2531618_0
  - absl-py=0.15.0=pyhd3eb1b0_0
  - aiohttp=3.8.1=py37h7f8727e_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - amqp=2.6.1=py_0
  - aniso8601=9.0.1=pyhd8ed1ab_0
  - asciitree=0.3.3=py_2
  - astor=0.8.1=py37h06a4308_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.1=pyhd3eb1b0_0
  - asynctest=0.13.0=py_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.10.0=pyh06a4308_0
  - billiard=3.6.4.0=py37h27cfd23_0
  - blas=1.0=mkl
  - blinker=1.4=py37h06a4308_0
  - blosc=1.21.0=h9c3ff4c_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py37h27cfd23_1003
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.26=h06a4308_2
  - cachetools=4.2.2=pyhd3eb1b0_0
  - celery=5.0.5=pyhd3eb1b0_0
  - certifi=2021.10.8=py37h06a4308_2
  - cffi=1.14.6=py37h400218f_0
  - chardet=4.0.0=py37h06a4308_1003
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.3=pyhd3eb1b0_0
  - click-didyoumean=0.0.3=pyhd3eb1b0_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - click-repl=0.2.0=pyhd3eb1b0_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - conda=4.11.0=py37h89c1867_0
  - conda-build=3.21.5=py37h06a4308_0
  - conda-package-handling=1.7.3=py37h27cfd23_1
  - coverage=5.5=py37h27cfd23_2
  - cryptography=3.4.8=py37hd23ed53_0
  - cudatoolkit=11.3.1=ha36c431_9
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=0.29.25=py37hdbfa776_0
  - cytoolz=0.11.0=py37h7b6447c_0
  - dask-core=2021.10.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - decorator=5.1.0=pyhd3eb1b0_0
  - fasteners=0.16.3=pyhd3eb1b0_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.0.12=pyhd3eb1b0_1
  - flask=1.1.2=pyhd3eb1b0_0
  - flask-redis=0.4.0=py_0
  - flask-restx=0.5.1=pyhd8ed1ab_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h5ab3b9f_0
  - frozenlist=1.2.0=py37h7f8727e_0
  - fsspec=2021.10.1=pyhd3eb1b0_0
  - future=0.18.2=py37_1
  - gast=0.3.3=py_0
  - giflib=5.2.1=h7b6447c_0
  - glob2=0.7=pyhd3eb1b0_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - greenlet=1.1.1=py37h295c915_0
  - grpc-cpp=1.36.4=hf89561c_1
  - grpcio=1.36.1=py37h2157cd5_1
  - h5py=2.10.0=py37hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=2.10=pyhd3eb1b0_0
  - imagecodecs=2021.3.31=py37hd0c323f_1
  - imageio=2.9.0=pyhd3eb1b0_0
  - importlib-metadata=4.8.2=py37h06a4308_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - ipython=7.27.0=py37hb070fc8_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jansson=2.14=h7f98852_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.0=py37h06a4308_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h7f8727e_0
  - jsonschema=4.4.0=pyhd8ed1ab_0
  - jxrlib=1.1=h7b6447c_2
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.3.1=py37h2531618_0
  - kombu=4.6.11=py37_0
  - krb5=1.19.2=hcc1bbae_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - lerc=2.2.1=h9c3ff4c_0
  - libaec=1.0.4=he6710b0_1
  - libarchive=3.5.2=hccf745f_1
  - libcurl=7.80.0=h0b77cf5_0
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.2=h7f8727e_0
  - liblief=0.10.1=he6710b0_0
  - libmamba=0.19.1=h3985d26_0
  - libmambapy=0.19.1=py37hab1676c_0
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.15.8=h780b84a_1
  - libsolv=0.7.19=h780b84a_5
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.3.0=hf544144_1
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxml2=2.9.12=h03d6c58_0
  - libzopfli=1.0.3=he6710b0_0
  - llvm-openmp=12.0.1=h4bd325d_1
  - locket=0.2.1=py37h06a4308_1
  - lz4-c=1.9.3=h295c915_1
  - lzo=2.10=h516909a_1000
  - mamba=0.19.1=py37h6dacc13_0
  - markdown=3.3.4=py37h06a4308_0
  - markupsafe=2.0.1=py37h27cfd23_0
  - matplotlib-base=3.4.3=py37hbbc1b5f_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.3.0=py37h54f3939_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - msgpack-python=1.0.2=py37hff7bd54_1
  - multidict=5.1.0=py37h27cfd23_2
  - munkres=1.1.4=py_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.6.3=pyhd3eb1b0_0
  - numcodecs=0.8.0=py37h2531618_0
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - olefile=0.46=py37_0
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1m=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=21.3=pyhd3eb1b0_0
  - parso=0.8.2=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_0
  - patchelf=0.13=h295c915_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pika=1.1.0=pyh9f0ad1d_1
  - pillow=8.4.0=py37h5aabda8_0
  - pip=21.0.1=py37h06a4308_0
  - pkginfo=1.7.1=py37h06a4308_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - protobuf=3.15.8=py37hcd2ae1e_0
  - psutil=5.8.0=py37h27cfd23_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py-lief=0.10.1=py37h403a769_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.3=py37h27cfd23_0
  - pycparser=2.20=py_2
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyjwt=2.1.0=py37h06a4308_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyrsistent=0.18.1=py37h5e8e339_0
  - pysocks=1.7.1=py37_1
  - python=3.7.11=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-flatbuffers=1.12=pyhd3eb1b0_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python_abi=3.7=2_cp37m
  - pytorch=1.10.0=py3.7_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - pywavelets=1.1.1=py37h7b6447c_2
  - pyyaml=5.3.1=py37h7b6447c_0
  - re2=2021.04.01=h9c3ff4c_0
  - readline=8.1=h27cfd23_0
  - redis-py=3.5.3=pyhd3eb1b0_0
  - reproc=14.2.3=h7f98852_0
  - reproc-cpp=14.2.3=h9c3ff4c_0
  - requests=2.25.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - ripgrep=12.1.1=0
  - rsa=4.7.2=pyhd3eb1b0_1
  - ruamel_yaml=0.15.87=py37h7b6447c_0
  - scikit-image=0.17.2=py37hdf5156a_0
  - scikit-learn=0.23.1=py37h423224d_0
  - scipy=1.4.1=py37h0b6359f_0
  - setuptools=58.0.4=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - snappy=1.1.8=he6710b0_0
  - soupsieve=2.2.1=pyhd3eb1b0_0
  - sqlalchemy=1.4.27=py37h7f8727e_0
  - sqlite=3.36.0=hc218d9a_0
  - tensorboard=2.4.0=pyhc547734_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorboardx=2.1=py_0
  - tensorflow=2.4.0=py37h89c1867_0
  - tensorflow-base=2.4.0=py37h00a14e9_0
  - tensorflow-estimator=2.4.0=pyh9656e83_0
  - termcolor=1.1.0=py37h06a4308_1
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2021.4.8=pyhd3eb1b0_2
  - tk=8.6.10=hbc83047_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchtext=0.11.0=py37
  - torchvision=0.11.0=py37_cu113
  - tornado=6.1=py37h27cfd23_0
  - tqdm=4.48.2=py_0
  - traitlets=5.1.0=pyhd3eb1b0_0
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021a=h52ac0ba_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - uwsgi=2.0.18=py37hd004684_2
  - vine=1.3.0=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - wrapt=1.13.3=py37h7f8727e_2
  - xz=5.2.5=h7b6447c_0
  - yaml=0.1.7=had09818_2
  - yaml-cpp=0.6.3=he1b5a44_4
  - yarl=1.6.3=py37h27cfd23_0
  - zarr=2.11.0=pyhd8ed1ab_0
  - zfp=0.5.5=h2531618_6
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - dnspython==2.1.0
    - ./elephant-core
    - nvsmi==0.4.2
    - python-etcd==0.4.5
    - torchelastic==0.2.0
